import React from 'react';

import { useAppSelector, } from '../hooks';
import { WeatherProvider, } from '../models';

import { Label, } from './Label';

type Icon = {
    openweathermap : { [ key : number ] : string, },
    accuweather    : { [ key : number ] : string, },
};

const DAY_ICONS : Icon = {
    openweathermap : {
        200 : 'wi-day-storm-showers',
        201 : 'wi-day-thunderstorm',
        202 : 'wi-day-thunderstorm',
        210 : 'wi-day-lightning',
        211 : 'wi-day-lightning',
        212 : 'wi-day-lightning',
        221 : 'wi-day-lightning',
        230 : 'wi-day-storm-showers',
        231 : 'wi-day-storm-showers',
        232 : 'wi-day-storm-showers',
        300 : 'wi-day-showers',
        301 : 'wi-day-showers',
        302 : 'wi-day-showers',
        310 : 'wi-day-showers',
        311 : 'wi-day-showers',
        312 : 'wi-day-showers',
        313 : 'wi-day-showers',
        314 : 'wi-day-showers',
        321 : 'wi-day-showers',
        500 : 'wi-day-rain',
        501 : 'wi-day-rain',
        502 : 'wi-day-rain',
        503 : 'wi-day-rain',
        504 : 'wi-day-rain',
        511 : 'wi-day-rain',
        520 : 'wi-day-rain',
        521 : 'wi-day-rain',
        522 : 'wi-day-rain',
        531 : 'wi-day-rain',
        600 : 'wi-day-snow',
        601 : 'wi-day-snow',
        602 : 'wi-day-snow',
        611 : 'wi-day-sleet',
        612 : 'wi-day-sleet',
        613 : 'wi-day-snow',
        615 : 'wi-day-snow',
        616 : 'wi-day-snow',
        620 : 'wi-day-snow',
        621 : 'wi-day-snow',
        622 : 'wi-day-snow',
        701 : 'wi-day-fog',
        711 : 'wi-smoke',
        721 : 'wi-day-haze',
        731 : 'wi-day-fog',
        741 : 'wi-day-fog',
        751 : 'wi-sandstorm',
        761 : 'wi-dust',
        762 : 'wi-dust',
        771 : 'wi-rain-wind',
        781 : 'wi-tornado',
        800 : 'wi-day-sunny',
        801 : 'wi-cloud',
        802 : 'wi-cloud',
        803 : 'wi-cloudy',
        804 : 'wi-cloudy',
    },
    accuweather    : {
        1  : 'wi-day-sunny',
        2  : 'wi-day-sunny',
        3  : 'wi-day-cloudy',
        4  : 'wi-day-cloudy',
        5  : 'wi-day-haze',
        6  : 'wi-cloudy',
        7  : 'wi-day-cloudy',
        8  : 'wi-day-sunny-overcast',
        11 : 'wi-day-fog',
        12 : 'wi-day-showers',
        13 : 'wi-showers',
        14 : 'wi-day-showers',
        15 : 'wi-day-thunderstorm',
        16 : 'wi-thunderstorm',
        17 : 'wi-day-thunderstorm',
        18 : 'wi-day-rain',
        19 : 'wi-sleet',
        20 : 'wi-sleet',
        21 : 'wi-day-sleet',
        22 : 'wi-day-snow',
        23 : 'wi-snow',
        24 : 'wi-snowflake-cold',
        25 : 'wi-sleet',
        26 : 'wi-rain',
        29 : 'wi-rain-mix',
        30 : 'wi-hot',
        31 : 'wi-snowflake-cold',
        32 : 'wi-strong-wind',
        33 : 'wi-night-clear',
        34 : 'wi-night-clear',
        35 : 'wi-night-alt-cloudy',
        36 : 'wi-night-alt-cloudy',
        37 : 'wi-night-fog',
        38 : 'wi-night-alt-cloudy',
        39 : 'wi-night-alt-showers',
        40 : 'wi-night-alt-showers',
        41 : 'wi-night-alt-thunderstorm',
        42 : 'wi-night-alt-thunderstorm',
        43 : 'wi-night-alt-sleet',
        44 : 'wi-night-alt-snow',
    },
};

const NIGHT_ICONS : Icon = {
    openweathermap : {
        200 : 'wi-night-alt-storm-showers',
        201 : 'wi-night-alt-thunderstorm',
        202 : 'wi-night-alt-thunderstorm',
        210 : 'wi-night-lightning',
        211 : 'wi-night-lightning',
        212 : 'wi-night-lightning',
        221 : 'wi-night-lightning',
        230 : 'wi-night-alt-storm-showers',
        231 : 'wi-night-alt-storm-showers',
        232 : 'wi-night-alt-storm-showers',
        300 : 'wi-night-alt-showers',
        301 : 'wi-night-alt-showers',
        302 : 'wi-night-alt-showers',
        310 : 'wi-night-alt-showers',
        311 : 'wi-night-alt-showers',
        312 : 'wi-night-alt-showers',
        313 : 'wi-night-alt-showers',
        314 : 'wi-night-alt-showers',
        321 : 'wi-night-alt-showers',
        500 : 'wi-night-alt-rain',
        501 : 'wi-night-alt-rain',
        502 : 'wi-night-alt-rain',
        503 : 'wi-night-alt-rain',
        504 : 'wi-night-alt-rain',
        511 : 'wi-night-alt-rain',
        520 : 'wi-night-alt-rain',
        521 : 'wi-night-alt-rain',
        522 : 'wi-night-alt-rain',
        531 : 'wi-night-alt-rain',
        600 : 'wi-night-alt-snow',
        601 : 'wi-night-alt-snow',
        602 : 'wi-night-alt-snow',
        611 : 'wi-night-alt-sleet',
        612 : 'wi-night-alt-sleet',
        613 : 'wi-night-alt-snow',
        615 : 'wi-night-alt-snow',
        616 : 'wi-night-alt-snow',
        620 : 'wi-night-alt-snow',
        621 : 'wi-night-alt-snow',
        622 : 'wi-night-alt-snow',
        701 : 'wi-night-fog',
        711 : 'wi-smoke',
        721 : 'wi-night-fog',
        731 : 'wi-night-fog',
        741 : 'wi-night-fog',
        751 : 'wi-sandstorm',
        761 : 'wi-dust',
        762 : 'wi-dust',
        771 : 'wi-night-alt-cloudy-windy',
        781 : 'wi-tornado',
        800 : 'wi-night-clear',
        801 : 'wi-cloud',
        802 : 'wi-cloud',
        803 : 'wi-night-alt-cloudy',
        804 : 'wi-night-alt-cloudy',
    },
    accuweather    : {
        1  : 'wi-day-sunny',
        2  : 'wi-day-sunny',
        3  : 'wi-day-cloudy',
        4  : 'wi-day-cloudy',
        5  : 'wi-day-haze',
        6  : 'wi-cloudy',
        7  : 'wi-day-cloudy',
        8  : 'wi-day-sunny-overcast',
        11 : 'wi-day-fog',
        12 : 'wi-day-showers',
        13 : 'wi-showers',
        14 : 'wi-day-showers',
        15 : 'wi-day-thunderstorm',
        16 : 'wi-thunderstorm',
        17 : 'wi-day-thunderstorm',
        18 : 'wi-day-rain',
        19 : 'wi-sleet',
        20 : 'wi-sleet',
        21 : 'wi-day-sleet',
        22 : 'wi-day-snow',
        23 : 'wi-snow',
        24 : 'wi-snowflake-cold',
        25 : 'wi-sleet',
        26 : 'wi-rain',
        29 : 'wi-rain-mix',
        30 : 'wi-hot',
        31 : 'wi-snowflake-cold',
        32 : 'wi-strong-wind',
        33 : 'wi-night-clear',
        34 : 'wi-night-clear',
        35 : 'wi-night-alt-cloudy',
        36 : 'wi-night-alt-cloudy',
        37 : 'wi-night-fog',
        38 : 'wi-night-alt-cloudy',
        39 : 'wi-night-alt-showers',
        40 : 'wi-night-alt-showers',
        41 : 'wi-night-alt-thunderstorm',
        42 : 'wi-night-alt-thunderstorm',
        43 : 'wi-night-alt-sleet',
        44 : 'wi-night-alt-snow',
    },
};

export const getWeatherIcon = ({
    weatherProvider,
    iconId,
    partOfDay = 'day',
} : {
    weatherProvider : 'accuweather' | 'openweathermap',
    iconId          : number,
    partOfDay?      : 'day' | 'night',
}) => partOfDay === 'night' ? NIGHT_ICONS[weatherProvider][iconId] : DAY_ICONS[weatherProvider][iconId];

export const WeatherIcon = ({
    iconId,
    partOfDay,
    description,
    ...rest
} : {
    iconId?           : number,
    partOfDay?        : 'day' | 'night',
    description?      : string,
    [ rest : string ] : any,
}) => {
    const weatherProvider : WeatherProvider = useAppSelector(state => state.settings.weatherProvider);

    return (
        <Label
            {...rest}
            tooltip={description}>
            <i className={`wi ${iconId ? getWeatherIcon({
                weatherProvider,
                iconId,
                partOfDay,
            }) : 'wi-na'}`} />
        </Label>
    );
};
